database:
  # the name of your JDBC driver
  driverClass: com.microsoft.sqlserver.jdbc.SQLServerDriver

  # the username
  user: openskye
  # the password
  password: infobelt12

  # the JDBC URL
  url: "jdbc:sqlserver://database.infobelt.com:49431"

  # Hibernate dialect
  dialect: "org.hibernate.dialect.SQLServerDialect"

  # C3PO connection pool settings below
  # hibernate.connection.provider_class
  connectionProviderClass: org.hibernate.service.jdbc.connections.internal.C3P0ConnectionProvider

  # hibernate.c3p0.max_size
  poolMaxSize: 10

  # hibernate.c3p0.min_size
  poolMinSize: 1

  # hibernate.c3p0.timeout
  poolTimeOut: 0

  # hibernate.c3p0.idle_test_period in seconds
  poolIdleTestPeriod: 60

  # hibernate.c3p0.preferredTestQuery
  poolPreferredTestQuery: SELECT 1

  # hibernate.c3p0.testConnectionOnCheckout
  poolTestConnectionOnCheckout: true

  # poolConnectionMaxIdleTime
  poolConnectionMaxIdleTime: 3600

  # maxIdleTimeExcessConnections
  maxIdleTimeExcessConnections: 900

  # unreturnedConnectionTimeout
  unreturnedConnectionTimeout: 0

services:
  omr: org.openskye.metadata.impl.jpa.JPAObjectMetadataRepository
  oms: org.openskye.metadata.elasticsearch.ElasticSearchObjectMetadataSearch
  taskManager: org.openskye.task.queue.QueueWorkerManager
  taskScheduler: org.openskye.task.quartz.QuartzTaskScheduler

search:
  host: localhost
  port: 9300

worker:
  # TODO you will need to specify a nodeID once you have created one
  # nodeId:
  hostname: atpblade05.infobelt.com
  threadCount: 5
  pollPeriodSec: 30

server:
  applicationConnectors:
    - type: http
      port: 5001
  adminConnectors:
    - type: http
      port: 9092

logging:
  level: INFO
  loggers:
    org.openskye: DEBUG
  appenders:
    - type: console

isMetricsDisabled: false