database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: root

  # the password
  password: password

  # the JDBC URL
  url: "jdbc:mysql://localhost/skye"

#http:
#    port: 5000
#    contextParameters:
#            swagger.api.basepath: http://localhost:8080
#            api.version: 1.0