database:
  driverClass: org.h2.Driver
  user: sa
  password:
  url: "jdbc:h2:mem:openskye"

services:
  omr: org.openskye.metadata.impl.jpa.JPAObjectMetadataRepository
  oms: org.openskye.metadata.impl.InMemoryObjectMetadataSearch
  taskManager: org.openskye.task.queue.TaskWorkerManager
  taskScheduler: org.openskye.task.quartz.QuartzTaskScheduler

server:
  applicationConnectors:
    - type: http
      port: 5000
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    org.openskye: INFO
  appenders:
    - type: console