# When using this config, run only SkyeWorker, not SkyeApplication
# The service and worker layers will run in one process

database:
  driverClass: org.h2.Driver
  user: sa
  password:
  url: "jdbc:h2:mem:openskye"
  dialect: "org.hibernate.dialect.H2Dialect"

services:
  omr: org.openskye.metadata.impl.jpa.JPAObjectMetadataRepository
  oms: org.openskye.metadata.impl.InMemoryObjectMetadataSearch
  taskManager: org.openskye.task.queue.QueueWorkerManager
  taskScheduler: org.openskye.task.quartz.QuartzTaskScheduler

worker:
  # TODO you will need to specify a nodeID once you have created one
  # nodeId:
  threadCount: 5
  pollPeriodSec: 30

server:
  applicationConnectors:
    - type: http
      port: 5000
  adminConnectors:
    - type: http
      port: 9091

logging:
  level: INFO
  loggers:
    org.openskye: INFO
  appenders:
    - type: console