database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: root

  # the password
  password: password

  # the JDBC URL
  url: "jdbc:mysql://localhost/openskye2"

  # Hibernate dialect
  dialect: "org.hibernate.dialect.MySQLDialect"
  
    # C3PO connection pool settings below
  # hibernate.connection.provider_class
  connectionProviderClass: org.hibernate.service.jdbc.connections.internal.C3P0ConnectionProvider 
  
  # hibernate.c3p0.max_size
  poolMaxSize: 100
  
  # hibernate.c3p0.min_size
  poolMinSize: 1
  
  # hibernate.c3p0.timeout
  poolTimeOut: 3600
  
  # hibernate.c3p0.max_statements
  poolMaxStatements: 100
  
  # hibernate.c3p0.idle_test_period in seconds
  poolIdleTestPeriod: 60
  
  # hibernate.connection.pool_size
  connectionPoolSize: 5

  # hibernate.c3p0.preferredTestQuery
  poolPreferredTestQuery: SELECT 1

  # hibernate.c3p0.testConnectionOnCheckout
  poolTestConnectionOnCheckout: false

services:
  omr: org.openskye.metadata.impl.jpa.JPAObjectMetadataRepository
  oms: org.openskye.metadata.elasticsearch.ElasticSearchObjectMetadataSearch
  taskManager: org.openskye.task.queue.QueueWorkerManager
  taskScheduler: org.openskye.task.quartz.QuartzTaskScheduler

worker:
  # TODO you will need to specify a nodeID once you have created one
  # nodeId:
  threadCount: 5
  pollPeriodSec: 30

server:
  applicationConnectors:
    - type: http
      port: 5001
  adminConnectors:
    - type: http
      port: 8082

logging:
  level: INFO
  loggers:
    org.openskye: DEBUG
  appenders:
    - type: console