database:
  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password:

  # the JDBC URL
  url: "jdbc:h2:mem:skye"

#http:
#    port: 5000
#    contextParameters:
#            swagger.api.basepath: http://localhost:5000
#            api.version: 1.0