database:
  
  driverClass: org.h2.Driver
  user: sa
  password:
  url: "jdbc:h2:mem:openskye"
  dialect: "org.hibernate.dialect.H2Dialect"

  # the name of your JDBC driver
  #driverClass: com.mysql.jdbc.Driver

  # the username
  #user: root

  # the password
  #password: password

  # the JDBC URL
  #url: "jdbc:mysql://localhost/openskye"

services:
  omr: org.openskye.metadata.impl.jpa.JPAObjectMetadataRepository
  oms: org.openskye.metadata.elasticsearch.ElasticSearchObjectMetadataSearch
  taskManager: org.openskye.task.queue.QueueWorkerManager
  taskScheduler: org.openskye.task.quartz.QuartzTaskScheduler

worker:
  name: "Skye Worker"
  threadCount: 5
  pollPeriodSec: 30

server:
  applicationConnectors:
    - type: http
      port: 5000
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    org.openskye: DEBUG
  appenders:
    - type: console
